### ISSUE TITLE
Simple variable name typo

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/hera_corr_f#2]
[Here](https://github.com/HERA-Team/hera_corr_f/blob/high-freq-res/control_software/src/blocks.py#L228): `reg_name` on one line, `regname` on another. (This is the high-freq-res branch, dunno about master.)

There are a lot of branches flying around so I'm not sure where I'd file a PR for this.

**Comment by jack-h** [comment]
Here, high-freq-res branch, please!

**Comment by pkgw** [comment]
Aw, you're gonna make me fix it myself? ... Well, GitHub let me edit the file through the website and commit directly to the branch without having to make a personal clone or PR, so that's what I did.

**Comment by jack-h** [comment]
I thought it best to set a precedent...
