### ISSUE TITLE
Programming logic fails to correctly decide if to reprogram

### ISSUE THREAD

**Issue by jack-h** [HERA-Team/hera_corr_f#3]
This doesn't do The Right Thing:

https://github.com/HERA-Team/hera_corr_f/blob/c3798a7a93c4659d6876658ab389dea71e6fd3bd/control_software/scripts/hera_snap_feng_init.py#L60

`get_metadata` doesn't return information on the running firmware, it returns information on the firmware residing in flash. These aren't the same thing after (eg) power on, when the SNAP is running the golden image.

**Comment by jack-h** [comment]
@dgorthi

**Comment by dgorthi** [comment]
I agree. I'm not sure how to check for the running firmware and not just the file on flash. I also realised that this piece of code is redundant to what casperfpga does anyway so I got rid of it.
