### ISSUE TITLE
Power cycle WR_SWITCH1

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_corr_f#39]
Node4 port was deactivated in history. We've reenabled it, but settings won't take until we power cycle. Also need to check that Node4 WR locks afterward.

**Comment by AaronParsons** [comment]
@jkocz Has this effectively been done, given your resent fix? If so, can you close the issue?

**Comment by jkocz** [comment]
I rebooted WR_SWITCH2 only. - Somewhat counterintuitively, this seems to be the primary switch (or at least the one in use on currently working nodes).
