### ISSUE TITLE
Some SNAPs have misconfigured network settings, sending packets to wrong X engine

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_corr_f#41]
Mentioned as an issue with the new h4cv2 branch code for configuring the eth blocks on snaps by @jkocz

**Comment by jkocz** [comment]
Inspection of configuration files showed they were correct. It appears to have been an offset in the memory on the FPGA, with the target IP address changing one clock cycle late. This has been fixed in a new F-engine code revision.
